environments:
  ci:
    requirements:
    - import: requirements.ci.txt
  dev:
    requirements:
    - import: requirements.dev.txt
python_version: '3.11'
requirements:
- import: requirements.txt
venv_directory: .venv
